use_frameworks!

#platform :ios, '10.0'

target 'TAAuthentication_Example' do
  pod 'TAAuthentication', :path => '../'
  pod 'Alamofire', '~> 5.4'
  pod 'ObjectMapper', '~> 4.2'
  pod 'SVProgressHUD'

  target 'TAAuthentication_Tests' do
    inherit! :search_paths

    
  end
end
